name: ProtoHackers CI

on:
  pull_request:
    branches: ["develop"]

jobs:
  tests:
    name: ${{ matrix.solution }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        solution: ["s2"]
        os: [ubuntu-latest]
        rust: [stable]
        make:
          - name: Unit tests
            task: cargo test --release
    steps:
    # Checkout Repo
    - uses: actions/checkout@v3

    - name: Install Rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
        components: rustfmt, clippy

    - name: ${{ matrix.make.name }}
      run: ${{ matrix.make.task }} --features ${{ matrix.solution }}
